apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: words
  namespace: '{{ meta.namespace }}'
  labels:
    app: words-api
spec:
  replicas: 5
  template:
    metadata:
      labels:
        app: words-api
    spec:
      containers:
      - name: words
        image: quay.io/loren123/api:latest
        ports:
        - containerPort: 8080
          name: api
